### PR TITLE
Icon library

### LINKED ISSUE #35: Build icon library
## Design spec

https://github.com/ubuntudesign/vanilla-dashboard-theme-design/tree/master/Icons

### PR DESCRIPTION
**Pull request by richmccartney**
## Done

- Created the full icon set for dashboard theme, icons will automatically take the current color of their parent. Error, Success and Warning are exempt from this rule

## QA

- Pull down the branch and check for any linting issues
- View icons on the light and dark pages

## Details

Fixes #35 

## Screenshots

[if relevant, include a screenshot]

### CODE REVIEW

**Comment by kwm14** [comment]
## Design review

- What colour have you applied to icons light? They should be `$color-mid-dark`
- 'User' is the incorrect icon
- Have you applied a 'stroke' to the icons? they don't look right compared to @spencerbygraves design spec seen here: https://github.com/ubuntudesign/vanilla-dashboard-theme-design/blob/master/Icons/Icon%20set.png

**Comment by richmccartney** [comment]
@kwm14 when I uploaded the user icon, its the same from here https://github.com/ubuntudesign/vanilla-dashboard-theme-design/blob/master/Icons/Icon%20set.md

There are no strokes or anything similar to the icons, they are just the same SVG's from the previous list I just posted.

Also icons will pick up the colour from the font colour, I've set them to be `#666` now but they will not inherit any colour now, so the demo I showed you earlier will never work when links or other messages can define the colour.

**Comment by kwm14** [comment]
@richmccartney thanks. I have spoken with Spencer and we're happy to roll with those icons, but we need to add another icon to the set which wasn't in the md.file.

- [ ] Add question icon - https://assets.ubuntu.com/v1/abda49e8-question_color_white.svg

**Comment by richmccartney** [comment]
@kwm14 take a nother look please :)

**Pull request merged**
