### PR TITLE
Framework cleanup

### PR DESCRIPTION
**Pull request by richmccartney**
## Done

- All SVGs have been optimised via SVGO and now embedded within the framework, removing the reliance of the asset server.
- Added improvements to the icon files, added the ability for the spinner to work on any background and removes the requirement for a different class.
- Renamed files and mixins to follow the VF naming principles.

## QA

- Pull down the branch, do `./run`
- Check locally all files load and all icons load too

### CODE REVIEW

**Comment by barrymcgee** [comment]
This is what I see for the animation util?

screen shot 2017-07-21 at 16 01 38

**Comment by barrymcgee** [comment]
If icons are specifically for the spinner icon, should they not be labelled as such?

**Comment by richmccartney** [comment]
@barrymcgee Ah nice catch on the animation, I forgot the `.p-` prefixes to the classes. 

Regards to the icons specificity. The idea is this should grow as more icons are added similar to what has been built on the MAAS GUI version of VF. There is already an icon set been designed by @spencerbygraves / @kwm14 this just sets up the ground work for it all 😄

**Comment by anthonydillon** [comment]
QA is good.

**Pull request merged**
