### PR TITLE
Bring in line with brochure theme

### PR DESCRIPTION
**Pull request by grahambancroft**
## Done

Bring in line with brochure theme

## QA

./run

### CODE REVIEW

**Comment by barrymcgee** [comment]
@grahambancroft The CSS is not loading for me?

screen shot 2017-07-17 at 14 25 09

**Comment by grahambancroft** [comment]
That’s odd. You may need to run 'npm rebuild node-sass —force'

**Comment by grahambancroft** [comment]
Ignore that last comment, should be okay now. Run ./run clean and try again

**Comment by barrymcgee** [comment]
👌🏻

**Pull request merged**
